# Generated by Django 5.1.7 on 2026-06-12 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_list', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон может содержать только цифры, пробелы, '+', '-' и скобки.", regex='^[0-9+\\-() ]{7,20}$')])),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
