# Generated by Django 5.2.13 on 2026-04-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='training_schedule',
        ),
    ]
