# Generated by Django 5.1.7 on 2026-06-12 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('notifications', '0002_expand_notifications'),
        ('schedule', '0003_initial'),
        ('subscriptions', '0003_initial'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.AddField(
            model_name='admin',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='admin',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='admin',
            name='subscriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='subscriptions.subscriptions'),
        ),
        migrations.AddField(
            model_name='admin',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='admin',
            name='training_schedule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='user_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.admin'),
        ),
        migrations.AddField(
            model_name='client',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='clients', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscriptions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='subscriptions.subscriptions'),
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='clients', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='training',
            field=models.ManyToManyField(blank=True, related_name='clients', to='schedule.training'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(default='Unknown trainer', max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать буквы.', regex='.*[^\\W\\d_].*')]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.TextField(default='General fitness'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainer',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='schedule.training'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать буквы.', regex='.*[^\\W\\d_].*')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Поле должно содержать буквы.', regex='.*[^\\W\\d_].*')]),
        ),
    ]
