# Generated by Django 6.0.1 on 2026-06-05 04:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('notifications', '0002_rename_content_notifications_message_and_more'),
        ('schedule', '0003_initial'),
        ('subscriptions', '0003_initial'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='bookings.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='admin',
            name='subscriptions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='subscriptions.subscriptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='users.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='training_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='user_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='clients', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscriptions',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='subscriptions.subscriptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='clients', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='training',
            field=models.ManyToManyField(blank=True, related_name='clients', to='schedule.training'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='notifications.notifications'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.TextField(default='Общая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='schedule.training'),
            preserve_default=False,
        ),
    ]
