# Generated by Django 5.2.13 on 2026-04-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='training',
        ),
        migrations.DeleteModel(
            name='ScheduledEvent',
        ),
        migrations.DeleteModel(
            name='TrainingSchedule',
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
