# Generated by Django 6.0.1 on 2026-06-05 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_remove_gym_training_delete_scheduledevent_and_more'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_content', models.TextField()),
                ('subscriptions_type', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('training_schedule', models.TextField()),
                ('max_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('equipment', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='users.admin')),
                ('clients', models.ManyToManyField(blank=True, related_name='gyms', to='users.client')),
                ('trainers', models.ManyToManyField(blank=True, related_name='gyms', to='users.trainer')),
                ('trainings', models.ManyToManyField(blank=True, related_name='gyms', to='schedule.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_data', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('workout_list', models.TextField()),
                ('free_seats', models.PositiveIntegerField()),
                ('gym', models.ManyToManyField(blank=True, related_name='schedules', to='schedule.gym')),
                ('trainer', models.ManyToManyField(blank=True, related_name='schedules', to='users.trainer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.training')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('free_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное колличество мест 1'), django.core.validators.MaxValueValidator(20, message='Максимальное колличество мест 20')])),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='schedule.gym')),
                ('trainer', models.ManyToManyField(blank=True, related_name='scheduled_events', to='users.trainer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to='schedule.training')),
                ('training_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.trainingschedule')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='schedule.trainingtype'),
        ),
    ]
