# Generated by Django 5.2.13 on 2026-04-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='SubscriptionsFreeze',
        ),
    ]
