# Generated by Django 6.0.1 on 2026-06-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('subscriptions', '0003_initial'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_task', models.TextField(blank=True)),
                ('free_seats', models.PositiveIntegerField()),
                ('active_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='subscriptions.subscriptions')),
                ('check_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='attendance.checkin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='users.client')),
            ],
        ),
    ]
