# Generated by Django 6.0.1 on 2026-06-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('schedule', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='schedule.training'),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.waitinglist'),
        ),
    ]
