# Generated by Django 5.1.7 on 2026-06-12 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0003_initial'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.TimeField()),
                ('active_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='subscriptions.subscriptions')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='users.admin')),
                ('check_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='attendance.checkin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='users.client')),
            ],
        ),
    ]
