# Generated by Django 5.1.7 on 2026-06-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('schedule', '0003_initial'),
        ('subscriptions', '0003_initial'),
        ('users', '0002_remove_admin_check_in_remove_admin_training_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='schedule.gym'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='subscriptions.subscriptions'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='schedule.training'),
        ),
    ]
