# Generated by Django 6.0.1 on 2026-06-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('schedule', '0003_initial'),
        ('subscriptions', '0003_initial'),
        ('users', '0003_rename_name_trainer_full_name_admin_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='schedule.gym'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='subscriptions.subscriptions'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_histories', to='schedule.training'),
        ),
    ]
